


//! TERMINOLOGI STANDARD LIBRARY GO


//! 1. APA ITU STANDARD LIBRARY GO?
//* STANDART LIBRARY GO ADALAH PACKAGE ATAU SEKUMPULAN MODULE YG DIMILIKI OLEH GOLANG


//TODO: MODULES = SEBUAH FILE YG BERISIKAN SEKUMPULAN CODE UNTUK MELAKUKAN SEBUAH TUGAS
//TODO: PACKAGE = SEBUAH TEMPAT | FOLDER YG BERISIKAN SEKUMPULAN MODULE

