

//! MATERI OPERATORS IN GOLANG


//! 1. APA ITU OPERATORS
/*
	OPERATOR ADALAH SEBUAH SIMBOL UNTUK MELAKUKAN OPERASI MATEMATIKA DI PROGRAMS
*/


//! 2. JENIS-JENIS OPERATOR YG ADA DI GOLANG

//! 2.1 OPERATOR ARITMATIK || AMATEMATIKA
/*
	TODO: OPERATOR YG DIGUNAKAN UNTKU MELAKUKAN OPERASI MATEMATIKA

	* 1. + = SIMBOL UNTUK MELAKUKAN OPERASI TAMBAH
	* 2. - = SIMBOL UNTUK MELAKUKAN OPERASI KURANG
	* 3. * = SIMBOL UNTUK MELAKUKAN OPERASI KALI
	* 4. / = SIMBOL UNTUK MELAKUKAN OPERASI BAGI
	* 5. % = SIMBOL UNTUK MELAKUKAN OPERASI MODULUS ATAU SISA BAGI
	* 6. () = SIMBOL UNTUK MELAKUKAN PRIORITAS PADA OPERASI MATEMATIKA
	

*/

//! 2.2 OPERATOR PENUGASAN
/*
	TODO: OPERATOR YG DIGUNAKAN UNTUK MELAKUKAN TUGAS TERTENTU

	* 1. A += B = OPEARATOR UNTUK MENAMBAHKAN NILAI 
	* 2. A -= B = OPEARATOR UNTUK MENGURANGI NILAI
	* 3. A *= B = OPEARATOR UNTUK MENGALAKUKAN KALIAN NILAI
	* 4. A /= B = OPEARATOR UNTUK MENGALAKUKAN BAGI NILAI
	* 5. A %= B = OPEARATOR UNTUK MENGALAKUKAN MODULUS NILAI


	TODO: UNARY OPERATOR ATAU OPERATOR YG HANYA MEMBUTUHKAN 1 NILAI
	* 1. ++A = OPEARATOR UNTUK MENAMBAH NILAI 1 KE SEBUAH NILAI
	* 2. --A = OPEARATOR UNTUK MENGURANGI NILAI 1 KE SEBUAH NILAI
	* 3. +A = OPEARATOR UNTUK MENJADI POSITIF SEBUAH NILAI
	* 4. -A = OPEARATOR UNTUK MENJADI NEGATIF SEBUAH NILAI
	* 5.!A = OPEARATOR UNTUK MENGUBAH TRUE JADI FALSE DAN SEBALIKNYA
	
*/

//! 2.3 OPERATOR PERBANDINGAN
/*
	TODO: OPERATOR UNTUK MELAKUKAN PERBANDINGAN ANTAR NILAI

	* 1. NILAI1 == NILAI2 = OPEARATOR UNTUK MEMABNDINGKAN APAKAH KEDUA NILAI KEDUA NILAI SAMA
	* 2. NILAI1 != NILAI2 = OPEARATOR UNTUK MEMABANDINGKAN APAKAH  KEDUA NILAI TIDAK SAMA
	* 3. NILAI1 < NILAI2 = OPEARATOR UNTUK MEMABANDINGKAN APAKAH  nilai1 lebih kecil dari nilai2
	* 4. NILAI1 > NILAI2 = OPEARATOR UNTUK MEMABANDINGKAN APAKAH  nilai1 lebih besar dari nilai2
	* 5. NILAI1 <= NILAI2 = OPEARATOR UNTUK MEMABANDINGKAN APAKAH  nilai1 lebih kecil atau sama dengan nilai2
	* 6. NILAI1 >= NILAI2 = OPEARATOR UNTUK MEMABANDINGKAN APAKAH  nilai1 lebih besar atau sama dengan nilai2

*/

//! 2.4 OPERATOR LOGIKA
/*
	TODO: OPERATOR UNTUK MELAKUKAN PERBANDINGAN KONDISI

	* 1. && = OPEARATOR UNTUK MEMBANDINGKAN 2 ATAU LEBIH KONDISI AKAN BERNILAI TRUE JIKA KEDUA KONDISINYA TERPENUHI ATAU TRUE
	* 2. || = OPEARATOR UNTUK MEMBANDINGKAN 2 ATAU LEBIH KONDISI AKAN BERNILAI TRUE JIKA SALAH SATU KONDISINYA TRUE
	* 3. ! = OPEARATOR UNTUK MENGUBAH TRUE JADI FALSE DAN SEBALIKNYA
	
*/