

//! TERMINOLOGI NILL DI GOLANG

//! 1. APA ITU NILL
/*
	? NILL ADALAH  nilai kosong/zero value khusus untuk tipe data reference seperti function,interface slice, map, dan channel
*/
//TODO: JADI NILL ITU BISA DI BILANG ADALAH NULL DI GOLANG
//TODO: TIDAK SEMUA TIPE DATA DI GOLANG DEFAULT VALUENYA NILL contohnya adalah string = "", int= 0, float =0 , dan boolean = false



//! 2. APA ITU TYPE ASSERTION
/*
	? TYPE ASSERTION ADALAH SEBUAH TEKNIK ATAU CARA UNTUK MEYAKINKAN GOLANG BAHWA SEBUAH NILAI AKAN MENJADI TIPE DATA TERTENTU
*/
//TODO:NOTES: KARENA KLO MISAL KITA MENGGUNAKAN INTERFACE KOSONG ATAU ANY GOLANG GATAU NILAI DENGAN TIPE DATA APA YG DI SIMPAN NANTI

//! 3. CARA MENGGUNAKAN TYPE ASSERTION
/*
	TODO:NOTES: KLO TIPE DATANYA TIDAK SESUAI DENGAN NILAI YG KITA TENTUKAN MAKA GOLANG AKAN PANIC ATAU MENAMPILKAN PESAN ERROR

	TODO: NOTES : BIASANYA KETIKA TYPE ASSERTION TERJADI PANIC ATAU ERROR KITA BISA TANGANIN MENGGUNAKAN SWITCH atau if else

	* syntax
	* value.(tipe_data)

	* contoh
	```
	* var data interface{} = "Hello World"
	* var str string = data.(string)
	```


*/
