

//! MATERI TIPE DATA DI GOLANG

//! 1. APA ITU TIPE DATA
/*
	TIPE DATA ATAU DATAYPE ADALAH SEBUAH JENIS DATA YG KITA BERIKAN DI PROGRAMN UNTUK MEMBERITAHUKAN KOMPUTER DATA APA YG AKAN KITA BUAT
*/

///todo: NOTES: SETIAP TIPE DATA MEMILIKI NILAI DEFAULTNYA MASING"

//! 2. MACAM-MACAM TIPE DATA DI GOLANG
// * ADA BEBERAPA TIPE DATA

//! 2.1 NUMBER
/*
	TODO: TIPE DATA UNTUK MEMBUAT ANGKA

	* INT = TIPE DATA UNTUK ANGKA BILANGAN BULAT (123)
	* FLOAT = TIPE DATA UNTUK ANGKA BILANGAN PECAHAN (1.2)
*/

//! 2.2 BOOLEAN
/*
	TODO: TIPE DATA UNTUK MENENTUKAN KEBENARAN

	* TRUE = TIPE DATA UNTUK BENAR
	* FALSE = TIPE DATA UNTUK SALAH
*/

//! 2.3 String
/*
	TODO: TIPE DATA UNTUK MEMBUAT KARAKTER
	TODO: CARA NYA DENGAN MENGGUNAKAN TANDA PETIK 2 ATAU "KARAKTER"

	TODO: len('karakter') = fungsi untuk menghitung panjang karakter
	TODO: "karater"[index || angka] ++ "karater"[0] = untuk mengambil kata pada karakter
*/